### ISSUE TITLE
evaluation for special character

### ISSUE THREAD

**Issue by vanche** [RuijieJ/pren#10]
Hi, thank you for your nice work ! 
I wanna ask about evaluation of your work.
Since some datasets include special character (out of vocab), the model can't predict these characters. 
In this case, if the model predict these unknown character as unk, did you accept it as correct or not in the reported performance? 
or did you just ignore all unk characters ? 

thank you!

**Comment by RuijieJ** [comment]
Our test protocol follows some previous works where words with special characters have been removed (e.g., for the IC13 we use the 857 version, and for the IC15 we use the 1811 version). For the IIIT5k test set,  we ignore special characters in groundtruth.

**Comment by vanche** [comment]
Thank you for the clear explanation ! :)
