### ISSUE TITLE
question about notation of the paper

### ISSUE THREAD

**Issue by vanche** [RuijieJ/pren#12]
Hi, 
I want to ask you about the notation of the paper.
In equation (11), what is x_j ?

**Comment by vanche** [comment]
I guessed it is same as g(N (fj )).

**Comment by RuijieJ** [comment]
Sorry, this is a typo, x_j is actually f_j, we only do convolutions on queries and keys. You can refer [this paper](https://ieeexplore.ieee.org/document/9413166) for more details about the encoder-decoder module.

**Comment by vanche** [comment]
I got it ! Thank you for the answer.
