### ISSUE TITLE
关于论文中的GCN的代码问题

### ISSUE THREAD

**Issue by simplify23** [RuijieJ/pren#15]
作者，你好，论文的GCN在源代码的实现中，使用了一个1d卷积+全连接的表现形式。据我所知，GCN应该是图卷积的意思，图卷积似乎并不是这样的表达，不知道是否我的理解有问题，希望能获得作者的解惑，非常感谢！

**Comment by RuijieJ** [comment]
[一个经典的图卷积网络工作](https://arxiv.org/abs/1609.02907)给出的图卷积表达式为

Z = (D^-0.5)A(D^-0.5)XW

A和D分别从邻接矩阵和度矩阵得到。由于我们没有显式的图结构表示，所以让A和D随着网络一起学习，并且把(D^-0.5)A(D^-0.5)统一成一个可学习参数B。1d卷积和全连接是等价的，避免对特征的转置。[这篇文章](https://arxiv.org/abs/1811.12814)也采用了类似的方式。

另外我们这里的参数B不是方阵，因此只是类似于一个GCN，并不完全等价。

**Comment by simplify23** [comment]
了解了，感谢作者
