### ISSUE TITLE
Pretrained model ?

### ISSUE THREAD

**Issue by ThorPham** [RuijieJ/pren#6]
Hello, many thanks to your excellent work!  I can't download weight in server baidu. Can you upload on google driver or send by email dungpv.ai@gmail.com Thank so much.

**Comment by RuijieJ** [comment]
Hi, I have sent you an email.

**Comment by ThorPham** [comment]
Thank so much

**Comment by Emna491** [comment]
Hello @ThorPham 
I also couldn't download the pre-trained model using Baidu. Could you please send it to my email: gitemna2022@gmail.com?

**Comment by ThorPham** [comment]
Sorry  i has deleted weight and link down no longer .

**Comment by RuijieJ** [comment]
> Hello @ThorPham I also couldn't download the pre-trained model using Baidu. Could you please send it to my email: [gitemna2022@gmail.com](mailto:gitemna2022@gmail.com)?

Hi, I have sent you the pretrained model.

**Comment by Emna491** [comment]
Thanks @RuijieJ  , well received :)
